### ISSUE TITLE
`terraform apply` is asking for additional input for Terraform v0.4.0+

### ISSUE THREAD

**Issue by onsi** [cloudfoundry-incubator/lattice#83] opened 2015-04-08 19:21 UTC

**Comment by davidwadden** [comment] 2015-04-14 14:29
This seems to be an issue with terraform introduced with their v0.4 release, and seemed to affect only the AWS platform.   It was fixed with the v0.4.2 release, and we've tested our terraform configs work with all the supported platforms.  The below issues offer more detail on the underlying root cause:

https://github.com/hashicorp/terraform/issues/1466
https://github.com/hashicorp/terraform/pull/1470

We changed the CI pipeline docker image to now use Terraform v0.4.2, and we've updated the README to reflect this is now the minimum supported version.

https://github.com/cloudfoundry-incubator/lattice/commit/772ed5afd018f8400636f34889ec7581823403a0
https://github.com/cloudfoundry-incubator/lattice/commit/2231ec43bed056f98a2c869359bf32d2405fdc8c

**Closed by davidwadden** 2015-04-14 14:29 UTC
