### ISSUE TITLE
Vagrant up fails

### ISSUE THREAD

**Issue by lalithvaka** [cloudfoundry-incubator/lattice#122] opened 2015-05-21 00:06 UTC
I am trying to install the lattice on my Mac which fails when I try vagrant up with the following msg

vagrant up --provider virtualbox
proxyconf...
find proxyconf plugin !
http_proxy: http://sjc1intproxy01.crd.ge.com:8080
https_proxy: http://sjc1intproxy01.crd.ge.com:8080
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'lattice/ubuntu-trusty-64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 0.2.0
The box 'lattice/ubuntu-trusty-64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/lattice/ubuntu-trusty-64"]
Error: 

appreciate any help.

**Comment by lalithvaka** [comment] 2015-05-21 00:38
My issue has been resolved. Not a vagrant expert but the following thread solved it
https://medium.com/@ritazzhang/vagrant-error-of-death-3c9ecb4aac9b

commenting out this block from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/subprocess.rb

if @command[0].downcase.include?(installer_dir)
@logger.info(“Command in the installer. Specifying DYLD_LIBRARY_PATH…”)
process.environment[“DYLD_LIBRARY_PATH”] =
“#{installer_dir}/lib:#{ENV[“DYLD_LIBRARY_PATH”]}”
@logger.info(“process.environment”)
@logger.info(process.environment[“DYLD_LIBRARY_PATH”])
@logger.info(“end process.environment”)
else
@logger.debug(“Command not in installer, not touching env vars.”)
end

**Comment by davidwadden** [comment] 2015-05-21 13:26
Okay, cool!  By the way, there's a newer version of Vagrant available - 1.7.2

If there's no outstanding issues, I'll go ahead and close this..

I did see from the last comment on mitchellh/vagrant#3589 an alternate fix that involves purging and re-installing;  apparently, the issue is at install-time when a certain OSX patch has been installed.

**Closed by davidwadden** 2015-05-21 13:26 UTC
