### ISSUE TITLE
[usage example] ltc droplet set of commands.

### ISSUE THREAD

**Issue by dhilipkumars** [cloudfoundry-incubator/lattice#147] opened 2015-07-17 14:45 UTC
Hello Lattice Team,

We are trying use lattice for a POC.  At the moment we are not interested in the longevity of these commands, so no worries we wont come back bugging you to keep them if you have decided to remove them later. :-)

I went through the story `(upload-bits)` and epic `(droplet set of commands)` of these new commands.   What i would really love to see is an overall usage examples of these commands. 
  
1) Creating a droplet (go)
2) uploading the my app bits 
3) Running my app.

Even if you have any screen run (putty output) that would demonstrate the order and usage of these commands coherently that would be great for me to start with. 

Thanks in Advance,
Dhilip

PS: if you have such screen dump already I will be a perfectly happy man to see them in this issue itself rather than waiting for that to be updated in the Readme.md :D

**Comment by menicosia** [comment] 2015-07-17 14:46
Hi @dhilipkumars,

Sure, no problem! I'll post the transcript of one of my acceptance runs later today.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by menicosia** [comment] 2015-07-17 15:47
Hi @dhilipkumars,

Your team (or anyone) should be able to do exactly this

```
$ CONDENSER_ON=1 vagrant up --provider=virtualbox

$ ltc target 192.168.11.11.xip.io

$ ltc target-blob 192.168.11.11:8980
[You'll need to input the S3 credentials printed in the `vagrant up` output]

$ cd ~/workspace/
$ git clone 'https://github.com/pivotal-cf-experimental/lattice-app.git'

$ ltc build-droplet LAPP go
Submitted build of LAPP
07/17 08:32:19.42 [BUILD|0] Successfully created container
07/17 08:32:19.94 [BUILD|0] Downloaded s3://condenser-bucket/LAPP/bits.tgz to /tmp/bits.tgz.
07/17 08:32:19.94 [BUILD|0] Exit status 0
07/17 08:32:19.96 [BUILD|0] Exit status 0
07/17 08:32:19.98 [BUILD|0] Exit status 0
07/17 08:32:35.75 [BUILD|0] -------> Buildpack version 1.4.0
07/17 08:32:43.34 [BUILD|0] -----> Installing go1.4.2... done
07/17 08:32:43.36 [BUILD|0] -----> Running: godep go install -tags cloudfoundry ./...
07/17 08:32:53.83 [BUILD|0] Exit status 0
07/17 08:32:53.96 [BUILD|0] Uploaded /tmp/droplet to s3://condenser-bucket/LAPP/droplet.tgz.
07/17 08:32:53.96 [BUILD|0] Exit status 0
07/17 08:32:54.03 [BUILD|0] Uploaded /tmp/result.json to s3://condenser-bucket/LAPP/result.json.
07/17 08:32:54.03 [BUILD|0] Exit status 0
Build completed


$ ltc launch-droplet LAPP LAPP
No port specified. Defaulting to 8080.
Creating App: LAPP
.07/17 08:36:02.33 [APP|0] Creating container
07/17 08:36:02.65 [APP|0] Successfully created container
07/17 08:36:03.29 [APP|0] Downloaded s3://condenser-bucket/LAPP/droplet.tgz to /tmp/droplet.tgz.
07/17 08:36:03.30 [APP|0] Exit status 0
.07/17 08:36:03.38 [APP|0] Exit status 0
07/17 08:36:03.41 [APP|0] {"timestamp":"1437147363.409129143","source":"lattice-app","message":"lattice-app.lattice-app.starting","log_level":1,"data":{"port":"8080"}}
07/17 08:36:03.41 [APP|0] {"timestamp":"1437147363.410006762","source":"lattice-app","message":"lattice-app.lattice-app.up","log_level":1,"data":{"port":"8080"}}
07/17 08:36:03.90 [HEALTH|0] healthcheck passed
07/17 08:36:03.90 [HEALTH|0] Exit status 0

LAPP is now running.
App is reachable at:
http://LAPP.192.168.11.11.xip.io
```

Easy, right? That's the first 80% of the Condenser project. The second 80% will be getting it to work on Terraform-deployed clusters, and polishing the hand-offs between Lattice and the Buildpacks such that each of the BPs works as expected, and as you suggested, providing some nice documentation.

I'm going to close this issue for now (example provided), but please feel free to re-open if you have any further questions!

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Closed by menicosia** 2015-07-17 15:47 UTC

**Comment by dhilipkumars** [comment] 2015-07-17 17:11
Thank you very much for the quick response.  I will agree with you on how easy it is after I try them tomorrow.  :-)

**Comment by dhilipkumars** [comment] 2015-07-19 07:50
@menicosia   Thanks again was not able to get lattice working in a new environment primarily because of proxy problems which prevents from downloading any sort of artifact from within the garden-linux Container. :-(  Which is why i thought i will try these new commands to run an app locally.  That did not work aswell because it needs buildpacks to be downloaded. :-(

 buildpacks are downloaded by the container?

one feedback if we are using `VAGRANT_HTTP_PROXY` and `VAGRANT_HTTPS_PROXY` variables to `vagrant up` lattice then we must also use `VAGRANT_NO_PROXY` otherwise condencer-bucket. 

below curl would fail.
```
curl -s -H 'Content-Type: application/json' -XPOST http://localhost:8980/riak-cs/user --data '{"email":"admin@lattice.cf", "name":"admin_user"}'
```

**Comment by menicosia** [comment] 2015-07-21 05:49
Hi @dhilipkumars,

Yes, the initial versions of Condenser assume that the customer has Internet access, though we didn't consider how using a proxy may affect this. Offline, or 'cached' buildpacks are on the backlog, see story [97208298](https://www.pivotaltracker.com/story/show/97208298).

I've created story [99488174](https://www.pivotaltracker.com/story/show/99488174) to account for this. We'll look into it, unless you have a fix in mind, and would like to submit a PR?

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by menicosia** [comment] 2015-07-21 14:07
Hi @dhilipkumars,

I realized you've actually pointed out two bugs; the first being the workaround you mentioned in order to talk to your own blobstore, the second is that buildpacks may not support HTTP proxy functionality.

I've created a story for the first: [99515656](https://www.pivotaltracker.com/story/show/99515656) and the additional story I've already mentioned above.

Thank you much! Feedback like this is very helpful.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by dhilipkumars** [comment] 2015-07-22 05:35
@menicosia Thanks for considering my feedback.  I somehow strongly feel that the proxy related problem needs to be fixed from garden-linux side.  I did raise an [issue] ( https://github.com/cloudfoundry-incubator/garden-linux/issues/24) long back but i was unable to prove it :-(.  

May be these problems are very specific to bosh-lite/vagrant installations like ours.  We have not tried with a real clustered setup yet.  

Thanks again for the help.

**Comment by menicosia** [comment] 2015-08-06 18:20
@dhilipkumars,

We've been going around and around on this proxy stuff. Sometimes things aren't as simple as they seem, take for example, this story: [Condenser should download dependencies through an HTTP proxy when configured](https://www.pivotaltracker.com/story/show/99488174).

This seems relatively straightforward, but in fact it is not. The problem is the `ltc` command line instructs Diego on all aspects of the build process's environment - the HTTP_PROXY settings used to deploy the cluster do not apply.

Thus, solving the proxy issue programmatically is a problem - the cluster needs to pass its state back to `ltc` so that `ltc` can know to send it back to the cluster... ugh.

An alternative, though, is not necessarily to set `VAGRANT_NO_PROXY`, but rather to supply the build environment with the PROXY information:
> $ ltc build-droplet LAPP BUILDPACK --env http_proxy=http://192.168.11.1:3128

What do you think? If this is acceptable, would you mind testing it in your environment? If it works well for you, I'll update the documentation to reflect this suggestion.

--

**Comment by dhilipkumars** [comment] 2015-08-13 04:59
@menicosia Apologies for the delay in responding.  I did spend some time last week to test this but was getting the below error
```
ltc build-droplet LAPP 'https://github.com/cloudfoundry/go-buildpack.git' --env https_proxy=https://10.18.204.244:3128
Error uploading to LAPP: 302 Proxy_Redirected
```

I think i need to update Lattice to the latest for this to work.  I will get back to on this shortly.   Thanks for help.
