### ISSUE TITLE
Boot2Docker v1.7.0 and Private Docker Registry?

### ISSUE THREAD

**Issue by trisberg** [cloudfoundry-incubator/lattice#143] opened 2015-07-13 20:30 UTC
Tried using a private Docker registry with Boot2Docker v1.7.0 and Lattice v0.2.6. Can't even get the Docker part working following the instructions here: http://lattice.cf/docs/private-docker-registry/

I get this error trying to access docker: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103

Same setup seems to work OK with Boot2Docker v1.6.2. Anyone else seeing this or have a fix?

**Comment by hsiliev** [comment] 2015-07-13 20:33
The problem is caused by Boot2Docker not waiting for eth1 to show up. More info and workaround can be found here:
https://gist.github.com/garthk/d5a17007c277aa5c76de

**Comment by trisberg** [comment] 2015-07-13 20:52
Thanks, should we add a note to the docs? They say "Using the latest http://boot2docker.io/" which is v1.7.0.

**Comment by menicosia** [comment] 2015-07-14 23:11
Hi @trisberg,

It looks like [boot2docker#960](https://github.com/boot2docker/boot2docker/pull/960) is merged and will be available in boot2docker 1.7.1.

I added a warning in the [release notes](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.2.6) and a warning in the [private docker registry](https://github.com/cloudfoundry-incubator/lattice/blob/develop/docs/private-docker-registry.md) document.

Thanks for the call-out!

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Closed by menicosia** 2015-07-14 23:11 UTC
