### ISSUE TITLE
Broken permissions on v0.2.0-7-g9f930ec release

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry-incubator/lattice#46] opened 2015-03-23 16:04 UTC
Hello!

I have no rights to download this tar:
```
HTTP request sent, awaiting response... 403 Forbidden
```

Deployment fails with errors:
```
Downloading Lattice Release tar from https://s3-us-west-2.amazonaws.com/lattice/releases/v0.2.0-7-g9f930ec/lattice.tgz => /home/demo/lattice/.lattice/lattice.tgz
...

module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): Connected! Executing scripts...
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): tar: This does not look like a tar archive

module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): gzip: stdin: unexpected end of file
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): tar: Child returned status 1
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): tar: Error is not recoverable: exiting now
```

**Comment by davidwadden** [comment] 2015-03-23 16:57
Can you provide some more details about what platform you're running on?  I attempted to reproduce this locally and it worked fine.

I can tell what the problem is -- our scripts are wrongly identifying "v0.2.0-7-g9f930ec" as being a release version rather than an unstable version.  We do some pattern matching on the contents of the Version file to determine whether it's formatted like our unstable or release versions.

Would you mind giving me the output from the following:

```
cd /home/demo/lattice
egrep '\-\d+-g[0-9a-fA-F]{7,10}$' Version
echo $?
egrep --version
```

my output:
```
± dw+kk |develop ✓| → egrep '\-\d+-g[0-9a-fA-F]{7,10}$' Version
v0.2.0-7-g9f930ec
± dw+kk |develop ✓| → echo $?
0
± dw+kk |develop ✓| → egrep --version
egrep (BSD grep) 2.5.1-FreeBSD
```

terraform apply output (not the /unstable/ path instead of /releases/)
```
module.lattice-aws.aws_route_table_association.lattice-network: Creation complete
module.lattice-aws.aws_instance.lattice-coordinator: Provisioning with 'local-exec'...
module.lattice-aws.aws_instance.lattice-coordinator (local-exec): Executing: /bin/sh -c "LOCAL_LATTICE_TAR_PATH=.lattice/lattice.tgz LATTICE_VERSION_FILE_PATH=/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry-incubator/lattice/aws-terraform-playground/.terraform/modules/d23447c3d09f3485679e8999f1ac3dcc/terraform/aws/../../Version /Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry-incubator/lattice/aws-terraform-playground/.terraform/modules/d23447c3d09f3485679e8999f1ac3dcc/terraform/aws/../local-scripts/download-lattice-tar"
module.lattice-aws.aws_instance.lattice-coordinator (local-exec): v0.2.0-7-g9f930ec
module.lattice-aws.aws_instance.lattice-coordinator (local-exec): Downloading Lattice Release tar from https://s3-us-west-2.amazonaws.com/lattice/unstable/v0.2.0-7-g9f930ec/lattice.tgz => /Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry-incubator/lattice/aws-terraform-playground/.lattice/lattice.tgz
module.lattice-aws.aws_instance.lattice-coordinator (local-exec): Download complete
module.lattice-aws.aws_instance.lattice-coordinator: Provisioning with 'file'...
```

**Comment by preillyme** [comment] 2015-03-29 16:56
It seems to work for me as well.

**Comment by onsi** [comment] 2015-03-30 20:08
@lexsys27 we're going to close this out.  Let's us know if it's still an issue for you.

**Closed by onsi** 2015-03-30 20:08 UTC

**Comment by lexsys27** [comment] 2015-03-31 09:17
Sorry for late answer! We have lost the instance in question and I couldn't manage to reproduce this issue today. So its ok to close.

**Comment by davidwadden** [comment] 2015-04-09 22:28
By the way, it looks like we identified some faulty parsing logic in the terraform scripts that decides to download a release or unstable build that only affected Linux users.  This has been corrected and should be available in the latest unstable build.

https://github.com/cloudfoundry-incubator/lattice/issues/72

**Comment by lexsys27** [comment] 2015-04-10 05:51
Nice to hear it!
