### ISSUE TITLE
Unable to run healthcheck in tutum/hello-world

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry-incubator/lattice#125] opened 2015-05-26 11:31 UTC
```bash
$ ltc create test tutum/hello-world
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 80
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 80...
No start command specified, using start command from the image metadata...
Start command is:
/bin/sh -c php-fpm -d variables_order="EGPCS" && exec nginx -g "daemon off;"
Creating App: test
26 May 14:29 [APP|0] Creating container
......26 May 14:29 [APP|0] Successfully created container
.26 May 14:29 [APP|0] [26-May-2015 11:29:09] ERROR: failed to open error_log (/var/log/php-fpm.log): Permission denied (13)
26 May 14:29 [APP|0] [26-May-2015 11:29:09] ERROR: failed to post process the configuration
26 May 14:29 [APP|0] [26-May-2015 11:29:09] ERROR: FPM initialization failed
26 May 14:29 [APP|0] Exit status 78
26 May 14:29 [APP|0] Creating container
...26 May 14:29 [APP|0] Successfully created container
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: failed to open error_log (/var/log/php-fpm.log): Permission denied (13)
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: failed to post process the configuration
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: FPM initialization failed
26 May 14:29 [APP|0] Exit status 78
.26 May 14:29 [APP|0] Creating container
```

Same with `-r`:
```bash
$ ltc create test tutum/hello-world -r
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 80
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 80...
No start command specified, using start command from the image metadata...
Start command is:
/bin/sh -c php-fpm -d variables_order="EGPCS" && exec nginx -g "daemon off;"
Creating App: test
.26 May 14:30 [APP|0] Creating container
...26 May 14:30 [APP|0] Successfully created container
26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
.26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
.26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
```

Image source:
https://github.com/tutumcloud/docker-hello-world

**Comment by bsideup** [comment] 2015-06-16 11:22
Any updates on this?

**Comment by menicosia** [comment] 2015-06-16 14:38
Hi @bsideup,

I've been super busy the last few weeks. We're trying to pare down outstanding issues, I will make sure to try to replicate your issue this week.

And per the standard questions: Have you tried this on Lattice v0.2.5, does this continue to work on versions of Lattice < 0.2.4, are you running on Vagrant or a Terraform-deployed cluster?

Sorry for the delays.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by bsideup** [comment] 2015-06-16 14:41
Hey @menicosia,

NP.

I will try with 0.2.5 now.

I'm running local Vagrant

**Comment by bsideup** [comment] 2015-06-19 10:51
@menicosia No, issue is still there (v 0.2.5)

**Comment by menicosia** [comment] 2015-07-14 23:52
Hi @bsideup,

Whelp, we've pushed forward and released v0.2.6, but I'm doubtful that it will solve your problem. I have a little quiet time this afternoon, so I looked a little more closely at your error output. This jumped out at me:
```
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: failed to open error_log (/var/log/php-fpm.log): Permission denied (13)
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: failed to post process the configuration
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: FPM initialization failed
```
This looks like it's likely an issue with how your container and OS are configured; we don't control the permissions of `/var/log`?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by bsideup** [comment] 2015-07-15 05:47
Hi!

Actually I don't know the root cause of issue and how this image configured
inside (see image source link), but this image works totally fine in
Docker, so it's definitely a problem with Warden


BTW so you have any plans to adopt runc? It will solve all such issues

**Comment by bsideup** [comment] 2015-07-15 07:12
@menicosia 

BTW have you checked it with "-r" (see log in issue)? It fails with different error:
```
26 May 14:30 [APP|0] Successfully created container
26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
```

**Comment by shinji62** [comment] 2015-07-19 17:54
Hi,

I have the same problem on a different docker image, run well on 0.2.3 but don t run on the 0.2.6.

In fact that's not really true, I use the 0.2.3 ltc client on the 0.2.6 cluster and my docker image work.
but using the 0.2.6 client my docker image do not start due to permission problem on file ..

```
......07/20 02:47:43.98 [APP|0] Successfully created container
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/autoload.php': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/philo/laravel-blade/src/Blade.php': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/philo/laravel-blade/src': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/philo/laravel-blade/composer.json': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/philo/laravel-blade/.gitignore': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/philo/laravel-blade/readme.md': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/philo/laravel-blade': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/philo': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/symfony/finder/Symfony/Component/Finder/Finder.php': Operation not permitted
07/20 02:47:44.15 [APP|0] chown: changing ownership of '/app/vendor/symfony/finder/Symfony/Component/Finder/Iterator/PathFilterIterator.php': Operation not permitted
```

```
ltc create gwenn-mongo getourneau/todo-php-mongo --run-as-root
```


and go to  http://gwenn-mongo.192.168.11.11.xip.io/alive.php

Can be a regression ??

**Comment by shinji62** [comment] 2015-07-22 03:14
Oh my problem seems resolve with the 0.2.7 version.. Thanks

**Comment by bsideup** [comment] 2015-07-22 07:40
Still presented in 0.2.7

**Comment by shinji62** [comment] 2015-07-22 09:46
Did you try run as root ??

**Comment by bsideup** [comment] 2015-07-22 10:16
@shinji62 yes :)

**Comment by davidwadden** [comment] 2015-07-22 11:56
Something is wonky with the healthcheck not firing inside of that docker image.

Anyways,  it comes up with:
`ltc create test tutum/hello-world -r --no-monitor`

```
06:50 $ ltc create test tutum/hello-world -r --no-monitor
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 80
No working directory specified, using working directory from the image metadata...
No ports will be monitored.
No start command specified, using start command from the image metadata...
Start command is:
/bin/sh -c php-fpm -d variables_order="EGPCS" && exec nginx -g "daemon off;"
Creating App: test
.07/22 06:51:09.46 [APP|0] Creating container
.07/22 06:51:11.39 [APP|0] Successfully created container
.
test is now running.
App is reachable at:
http://test.192.168.11.11.xip.io
```

But that disables healthchecking.

```
vagrant@ubuntu-trusty-64:~$ sudo /var/lattice/garden/depot/sq2bpnk4gsl/bin/wsh --socket /var/lattice/garden/depot/sq2bpnk4gsl/run/wshd.sock --user root --env CF_INSTANCE_ADDR=192.168.11.11:61010 --env CF_INSTANCE_IP=192.168.11.11 --env CF_INSTANCE_PORT=61010 --env CF_INSTANCE_PORTS=61010:80 --env INSTANCE_GUID=1e4f299f-e3d1-4f7f-7269-911e44d0c159 --env INSTANCE_INDEX=0 --env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env PORT=80 --env PROCESS_GUID=test --dir /
/tmp # ls -l healthcheck
-rwxr-xr-x    1 vcap     vcap       5981296 Jul 22 03:05 healthcheck
/tmp # ./healthcheck
/bin/sh: ./healthcheck: not found
```

this is when running on `cloudfoundry/lattice-app` -- 
```
/ $ /tmp/healthcheck
healthcheck passed
```

**Comment by bsideup** [comment] 2015-07-22 11:59
@davidwadden Dockerfile for this image (you can find it if you will follow the link from issue):
```
FROM alpine
MAINTAINER support@tutum.co
RUN apk --update add nginx php-fpm
RUN mkdir -p /tmp/nginx && echo "clear_env = no" >> /etc/php/php-fpm.conf
ADD www /www
ADD nginx.conf /etc/nginx/
EXPOSE 80
CMD php-fpm -d variables_order="EGPCS" && exec nginx -g "daemon off;"
```

`FROM alpine` - IMO it could break something

**Comment by jbayer** [comment] 2015-07-30 14:45
@julz thinks this will be addressed by having lattice pick up the latest garden-linux

_actually I think that's fixed in recent code, for a while we didn't have CAP_CHOWN in the list of whitelisted capabilities, which is why the chowns would be failing. So I think that'll be fixed by a garden-Linux bump_

**Comment by bsideup** [comment] 2015-07-31 11:49
@jbayer ok, lets wait for it then :)

**Comment by svrc-pivotal** [comment] 2015-09-16 13:55
I believe this is because `healthcheck` is dynamically linked due to a golang 1.4 change on how binaries are statically linked , see golang/go#9344 , and the `alpine` docker base image doesn't have the standard libc.  
```
$ ltc ssh test
Connecting to test/0 at 192.168.11.11.xip.io
/tmp # ldd /tmp/healthcheck
	/lib64/ld-linux-x86-64.so.2 (0x7f87e5869000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f87e5869000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f87e5869000)
Error relocating /tmp/healthcheck: __vfprintf_chk: symbol not found
````

**Comment by davidwadden** [comment] 2015-09-20 20:55
@bsideup 

Can you try again with our latest nightly build (**v0.4.3-29-g42e5d9e**) ?

They are available on our [nightly builds](https://lattice.s3.amazonaws.com/nightly/index.html) page.

```bash
$ vagrant ssh -c "cat /var/lattice/LATTICE_VERSION"
v0.4.3-29-g42e5d9e
$ ltc -v
ltc version v0.4.3-29-g42e5d9e (diego 0.1398.0)
$ ltc lg test
09/20 15:44:22.41 [HEALTH|0] healthcheck passed
09/20 15:44:22.41 [HEALTH|0] Exit status 0
09/20 15:44:52.46 [HEALTH|0] healthcheck passed
09/20 15:44:52.46 [HEALTH|0] Exit status 0
```

It seems to have worked .. but try for yourself and let us know

/cc @svrc-pivotal

**Comment by davidwadden** [comment] 2015-09-21 21:45
Detailed acceptance is available at [[#103511980](https://www.pivotaltracker.com/story/show/103511980)]

Closing issue.  It will land in our upcoming release.

**Closed** 2015-09-21 21:51 UTC
Labels: cluster

**Comment by bsideup** [comment] 2015-09-23 08:21
@davidwadden I tried and it's still failing:

```
Sergeis-MacBook-Pro:lattice-bundle-v0.4.4-4-gbb2a916-osx bsideup$ ./ltc create test tutum/hello-world
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 80
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 80...
No start command specified, using start command from the image metadata...
Start command is:
/bin/sh -c php-fpm -d variables_order="EGPCS" && exec nginx -g "daemon off;"
Creating App: test
......................09/23 11:20:17.81 [APP|0] Successfully created container
09/23 11:20:18.17 [APP|0] [23-Sep-2015 08:20:18] ERROR: failed to open error_log (/var/log/php-fpm.log): Permission denied (13)
09/23 11:20:18.17 [APP|0] [23-Sep-2015 08:20:18] ERROR: failed to post process the configuration
09/23 11:20:18.17 [APP|0] [23-Sep-2015 08:20:18] ERROR: FPM initialization failed
09/23 11:20:18.18 [APP|0] Exit status 78
09/23 11:20:18.27 [APP|0] {"timestamp":"1442996418.275834322","source":"sshd","message":"sshd.started","log_level":1,"data":{}}
.09/23 11:20:18.63 [HEALTH|0] healthcheck failed
09/23 11:20:18.65 [HEALTH|0] Exit status 1
```

**Comment by svrc-pivotal** [comment] 2015-09-23 11:21
That's a permission denied error ; You'll need the -r option on that command to run the Docker image as root.

**Comment by bsideup** [comment] 2015-09-23 11:24
@svrc-pivotal ok, working with -r. Looks like lattice is useless without "-r", maybe it should be enabled by default?

**Comment by svrc-pivotal** [comment] 2015-09-23 12:52
@bsideup Some Dockerfiles require root eg. toys like this tutum/hello-world.  It's not a necessity.  Running a Linux container as root is has historically been risky, especially in a multi tenant environment.

**Comment by svrc-pivotal** [comment] 2015-09-23 13:01
@bdiseup also - there is work to adopt runC behind Garden to eliminate future docker weirdness, though we may still have different security defaults :-)  

in this case the bug actually was because we inject a healthcheck process into /tmp that mistakenly wasn't statically linked in Lattice (it is in Cloud Foundry)

**Comment by davidwadden** [comment] 2015-09-23 14:49
There's a lot of reasons not to run your images as root.  We allow this functionality, but prefer the default to be a non-privileged user.  It is typically our first recommendation if an image is having problems though.
